
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Billing_Shipping_details
{

    public int id { get; set; }

    public string email { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string b_Adress { get; set; }

    public string city { get; set; }

    public string state { get; set; }

    public string zip_code { get; set; }

    public string country { get; set; }

    public string phone { get; set; }

    public string s_type { get; set; }

    public string s_name { get; set; }

    public string s_adress { get; set; }

    public string s_city { get; set; }

    public string s_state { get; set; }

    public string s_zip_code { get; set; }

    public string s_country { get; set; }

    public string s_suite { get; set; }

    public string b_suite { get; set; }

    public string s_phone { get; set; }

    public Nullable<bool> completed { get; set; }

    public Nullable<int> userid { get; set; }

    public Nullable<int> orderid { get; set; }



    public virtual marketing_orders marketing_orders { get; set; }

    public virtual Sys_Users Sys_Users { get; set; }

}

}
