
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class label_color
{

    public int id { get; set; }

    public string background { get; set; }

    public string color { get; set; }

    public int labelid { get; set; }

    public string label_name { get; set; }

    public string templateid { get; set; }



    public virtual Template_Details Template_Details { get; set; }

    public virtual label label { get; set; }

}

}
