
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class label
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public label()
    {

        this.saved_labels = new HashSet<saved_labels>();

        this.label_color = new HashSet<label_color>();

    }


    public int id { get; set; }

    public string template { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public string p_top { get; set; }

    public string p_bottom { get; set; }

    public string p_right { get; set; }

    public string p_left { get; set; }

    public string Font { get; set; }

    public string Color { get; set; }

    public string size { get; set; }

    public string width { get; set; }

    public string height { get; set; }

    public string pic_bottom { get; set; }

    public string pic_left { get; set; }

    public string font_weight { get; set; }

    public string text_position { get; set; }

    public string Font_type { get; set; }

    public string shape { get; set; }



    public virtual Template_Details Template_Details { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<saved_labels> saved_labels { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<label_color> label_color { get; set; }

}

}
