
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Marketing_order_details
{

    public int id { get; set; }

    public int order_id { get; set; }

    public string template { get; set; }

    public decimal unit_price { get; set; }

    public int items { get; set; }

    public System.DateTime creation_date { get; set; }



    public virtual Template_Details Template_Details { get; set; }

    public virtual marketing_orders marketing_orders { get; set; }

}

}
