
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Market_Categ_type
{

    public int id { get; set; }

    public int category { get; set; }

    public Nullable<int> subcategory { get; set; }

    public string name { get; set; }

    public string description { get; set; }

    public Nullable<int> business_card { get; set; }

    public Nullable<int> yard_signs { get; set; }

    public Nullable<int> riders { get; set; }

    public Nullable<int> open_house { get; set; }

    public Nullable<int> closing_signs { get; set; }

    public Nullable<int> for_sale_panels { get; set; }

}

}
