
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class saved_labels
{

    public int id { get; set; }

    public int labelid { get; set; }

    public string templateid { get; set; }

    public int saved_template { get; set; }

    public string text { get; set; }

    public Nullable<int> userid { get; set; }

    public string font_size { get; set; }

    public string color { get; set; }



    public virtual label label { get; set; }

    public virtual Template_Details Template_Details { get; set; }

    public virtual Sys_Users Sys_Users { get; set; }

}

}
