
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Saved_Templates
{

    public int id { get; set; }

    public string Templateid { get; set; }

    public string description { get; set; }

    public System.DateTime Creation_date { get; set; }

    public string Material { get; set; }

    public string Size { get; set; }

    public string Holes { get; set; }

    public Nullable<bool> Laminate { get; set; }

    public Nullable<bool> clearcoat { get; set; }

    public int category { get; set; }

    public int user_id { get; set; }

    public int label_num { get; set; }

    public string location { get; set; }

    public int amount { get; set; }

    public bool completed { get; set; }

    public string photo_path { get; set; }

    public string logo_path { get; set; }

    public Nullable<decimal> price { get; set; }

    public string Comments { get; set; }

    public Nullable<int> orderid { get; set; }

    public Nullable<int> type { get; set; }

    public Nullable<int> dimension { get; set; }

    public string path { get; set; }



    public virtual Template_Details Template_Details { get; set; }

    public virtual Template_categories Template_categories { get; set; }

    public virtual marketing_orders marketing_orders { get; set; }

    public virtual Template_type Template_type { get; set; }

    public virtual Template_dimensions Template_dimensions { get; set; }

    public virtual Sys_Users Sys_Users { get; set; }

}

}
