
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Shipping_Details
{

    public int id { get; set; }

    public string carrier { get; set; }

    public decimal price { get; set; }

    public string type { get; set; }

    public int dates { get; set; }

}

}
