
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Sys_Notifications
{

    public int ID_notification { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public System.DateTime Date { get; set; }

    public bool Active { get; set; }

    public int ID_user { get; set; }



    public virtual Sys_Users Sys_Users { get; set; }

}

}
