
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class T_Company_Type
{

    public int id { get; set; }

    public int type { get; set; }

    public int company { get; set; }

    public string path { get; set; }



    public virtual T_Company_Type T_Company_Type1 { get; set; }

    public virtual T_Company_Type T_Company_Type2 { get; set; }

    public virtual Template_categories Template_categories { get; set; }

}

}
