
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Customers
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_Customers()
    {

        this.Tb_Process = new HashSet<Tb_Process>();

    }


    public int ID_Customer { get; set; }

    public string Name { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }

    public System.DateTime Birthday { get; set; }

    public string Marital_status { get; set; }

    public string Type { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public string Mobile { get; set; }

    public string State { get; set; }

    public string Address { get; set; }

    public string Zipcode { get; set; }

    public bool Lead { get; set; }

    public bool Active { get; set; }

    public int ID_Company { get; set; }

    public System.DateTime Creation_date { get; set; }

    public string Source { get; set; }

    public Nullable<int> ID_team { get; set; }



    public virtual Sys_Company Sys_Company { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_Process> Tb_Process { get; set; }

}

}
