
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_Reminders
{

    public int ID_Reminder { get; set; }

    public int ID_User { get; set; }



    public virtual Sys_Users Sys_Users { get; set; }

}

}
