
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Realestate_portal.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Template_Details
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Template_Details()
    {

        this.labels = new HashSet<label>();

        this.Marketing_order_details = new HashSet<Marketing_order_details>();

        this.saved_labels = new HashSet<saved_labels>();

        this.Saved_Templates = new HashSet<Saved_Templates>();

        this.label_color = new HashSet<label_color>();

        this.Template_colors = new HashSet<Template_colors>();

    }


    public string id { get; set; }

    public int category { get; set; }

    public string path { get; set; }

    public string width { get; set; }

    public string height { get; set; }

    public string cleaned_path { get; set; }

    public string cleaned_name { get; set; }

    public bool header { get; set; }

    public bool company_name { get; set; }

    public bool agent_name { get; set; }

    public bool phone { get; set; }

    public bool photo { get; set; }

    public bool logo { get; set; }

    public bool website { get; set; }

    public bool title { get; set; }

    public bool email { get; set; }

    public bool profile_pic { get; set; }

    public string pic_path { get; set; }

    public string original_width { get; set; }

    public string original_height { get; set; }

    public string saved_width { get; set; }

    public string saved_height { get; set; }

    public string logo_path { get; set; }

    public Nullable<int> type { get; set; }

    public Nullable<decimal> price { get; set; }

    public Nullable<bool> message { get; set; }

    public Nullable<bool> other { get; set; }

    public Nullable<bool> adress_1 { get; set; }

    public Nullable<bool> adress_2 { get; set; }

    public Nullable<bool> pic_round { get; set; }

    public Nullable<bool> instagram { get; set; }

    public Nullable<bool> facebook { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<label> labels { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Marketing_order_details> Marketing_order_details { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<saved_labels> saved_labels { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Saved_Templates> Saved_Templates { get; set; }

    public virtual Template_categories Template_categories { get; set; }

    public virtual Template_type Template_type { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<label_color> label_color { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Template_colors> Template_colors { get; set; }

}

}
